[package]
name = "tokio-diesel"
version = "0.1.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
edition = "2018"
description = "Integrate Diesel into Tokio cleanly and efficiently."
repository = "https://github.com/mehcode/tokio-diesel"
license = "MIT/Apache-2.0"
categories = ["asynchronous", "database"]

[dependencies]
diesel = { version = "1.4.2", features = [ "r2d2" ] }
tokio = "0.1"
tokio-threadpool = "0.1"
futures-preview = "=0.3.0-alpha.16"
futures01 = { version = "0.1", package = "futures" }
r2d2 = "0.8"
parking_lot = "0.8"

[dev-dependencies]
runtime = "0.3.0-alpha.4"
runtime-tokio = "0.3.0-alpha.4"
diesel = { version = "1.4.2", features = [ "postgres", "uuidv07" ] }
failure = "0.1"
uuid = { version = "0.7", features = [ "v4" ] }
