[package]
name = "tokio-diesel"
version = "0.1.1"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
edition = "2018"
description = "Integrate Diesel into Tokio cleanly and efficiently."
repository = "https://github.com/mehcode/tokio-diesel"
license = "MIT/Apache-2.0"
categories = ["asynchronous", "database"]

[dependencies]
diesel = { version = "1.4.2", features = [ "r2d2" ] }
tokio-executor = "0.2.0-alpha.4"
futures-core-preview = "0.3.0-alpha.18"
r2d2 = "0.8.5"

[dev-dependencies]
diesel = { version = "1.4.2", features = [ "postgres", "uuidv07" ] }
uuid = { version = "0.7.4", features = [ "v4" ] }
tokio = { version = "0.2.0-alpha.4", default-features = false, features = [ "rt-full" ] }
